name = "alphagate-edge-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MAIN_APP_URL = "http://localhost:3001"
# PORTKEY_GATEWAY_URL = "https://your-portkey-gateway.example.com"
# PORTKEY_ORG_TOKEN = "pk_live_xxx"

# [[kv_namespaces]]
# binding = "CONFIG_CACHE"
# id = ""

# [[durable_objects.bindings]]
# name = "QUOTA_COUNTERS"
# class_name = "QuotaCounters"

# [[queues.producers]]
# binding = "USAGE_EVENTS"
# queue = "usage-events"
