name = "alphagate-edge-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

# [vars]
# SUPABASE_URL=""

# [[kv_namespaces]]
# binding = "CONFIG_CACHE"
# id = ""

# [[durable_objects.bindings]]
# name = "QUOTA_COUNTERS"
# class_name = "QuotaCounters"

# [[queues.producers]]
# binding = "USAGE_EVENTS"
# queue = "usage-events"

